const EventsActionTypes = {
    FETCH_EVENTS_START: 'FETCH_EVENTS_START',
    FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
    FETCH_EVENTS_FAILURE: 'FETCH_EVENTS_FAILURE',
    CREATE_EVENT_START: 'CREATE_EVENT_START',
    CREATE_EVENT_SUCCESS: 'CREATE_EVENT_SUCCESS',
    CREATE_EVENT_FAILURE: 'CREATE_EVENT_FAILURE',
}

export default EventsActionTypes