const ParticipationActionTypes = {
    FETCH_PARTICIPATION_START:'FETCH_PARTICIPATION_START',
    FETCH_PARTICIPATION_SUCCESS:'FETCH_PARTICIPATION_SUCCESS',
    FETCH_PARTICIPATION_FAILURE:'FETCH_PARTICIPATION_FAILURE',
    ADD_PARTICIPATION_START:'ADD_PARTICIPATION_START',
    ADD_PARTICIPATION_SUCCESS:'ADD_PARTICIPATION_SUCCESS',
    ADD_PARTICIPATION_FAILURE:'ADD_PARTICIPATION_FAILURE',
    REMOVE_PARTICIPATION_START:'REMOVE_PARTICIPATION_START',
    REMOVE_PARTICIPATION_SUCCESS:'REMOVE_PARTICIPATION_SUCCESS',
    REMOVE_PARTICIPATION_FAILURE:'REMOVE_PARTICIPATION_FAILURE',
}

export default ParticipationActionTypes